<?php

use Pinoox\Component\Template\Frontend\FrontendConfig;
use Pinoox\Component\Template\Frontend\FrontendDevSession;
use Pinoox\Component\Template\Frontend\FrontendDevSync;

const FRONTEND_DEV_SYNC_TEST_SERVE_PORT = 19800;

const FRONTEND_DEV_SYNC_ENV_KEYS = ['VITE_DEV_PORT', 'VITE_DEV', 'VITE_DEV_SERVER', 'VITE_DEV_FORCE'];

function frontendDevSyncEnvSnapshot(): array
{
    $snapshot = [];

    foreach (FRONTEND_DEV_SYNC_ENV_KEYS as $key) {
        $snapshot[$key] = $_ENV[$key] ?? null;
    }

    return $snapshot;
}

function frontendDevSyncEnvRestore(array $snapshot): void
{
    foreach ($snapshot as $key => $value) {
        if ($value === null) {
            unset($_ENV[$key], $_SERVER[$key]);
            putenv($key);
        } else {
            $_ENV[$key] = $value;
            $_SERVER[$key] = $value;
        }
    }
}

function frontendDevSyncThemeDir(): string
{
    // Mirror real apps/{pkg}/theme/{name} so dirname(dirname($theme)) is the app root.
    $appPath = sys_get_temp_dir() . '/pinoox-fe-sync-' . uniqid('', true);
    $themePath = $appPath . '/theme/default';
    mkdir($themePath, 0777, true);

    return $themePath;
}

function frontendDevSyncRemoveThemeDir(string $path): void
{
    if (!is_dir($path)) {
        return;
    }

    // Prefer removing the app root when the helper created …/theme/default.
    $normalized = rtrim(str_replace('\\', '/', $path), '/');
    if (str_ends_with($normalized, '/theme/default')) {
        $path = dirname($path, 2);
    }

    if (!is_dir($path)) {
        return;
    }

    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST,
    );

    foreach ($iterator as $item) {
        if ($item->isDir()) {
            @rmdir($item->getPathname());
        } else {
            @unlink($item->getPathname());
        }
    }

    @rmdir($path);
}

beforeEach(function () {
    $GLOBALS['__frontendDevSyncEnvSnapshot'] = frontendDevSyncEnvSnapshot();
});

afterEach(function () {
    if (isset($GLOBALS['__frontendDevSyncThemePath'])) {
        frontendDevSyncRemoveThemeDir($GLOBALS['__frontendDevSyncThemePath']);
        unset($GLOBALS['__frontendDevSyncThemePath']);
    }

    if (isset($GLOBALS['__frontendDevSyncEnvSnapshot'])) {
        frontendDevSyncEnvRestore($GLOBALS['__frontendDevSyncEnvSnapshot']);
        unset($GLOBALS['__frontendDevSyncEnvSnapshot']);
    }
});

test('FrontendDevSync sync leaves existing theme .env byte-for-byte unchanged', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    $originalEnv = "MY_CUSTOM=stay\nENV_SERVER_SYNC=true\n";
    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env', $originalEnv);

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session, false, '.env.local');

    expect($result['env_autodev'])->toBeFalse()
        ->and($result['env_seeded'])->toBeFalse()
        ->and(file_get_contents($themePath . '/.env'))->toBe($originalEnv);
});

test('FrontendDevSync sync does not create theme .env when missing', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env.example', "VITE_DEV_PORT=5199\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session);

    expect($result['env_seeded'])->toBeFalse()
        ->and(is_file($themePath . '/.env'))->toBeFalse()
        ->and(is_file($themePath . '/.env.local'))->toBeFalse();
});

test('FrontendDevSync sync-env persists autogenerated block to .env.local', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session, false, '.env.local', true);

    expect($result['env_autodev'])->toBeTrue()
        ->and(is_file($themePath . '/.env.local'))->toBeTrue()
        ->and(file_get_contents($themePath . '/.env.local'))->toContain('@pinoox-fe-dev autogenerated')
        ->and(file_get_contents($themePath . '/.env.local'))->toContain('VITE_DEV_PORT=' . $session->vitePort);
});

test('FrontendDevSync ENV_SERVER_SYNC in .env.local persists autogenerated block', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env.local', "ENV_SERVER_SYNC=true\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session);

    expect($result['env_autodev'])->toBeTrue()
        ->and(file_get_contents($themePath . '/.env.local'))->toContain('VITE_SERVER_URL=http://127.0.0.1:' . FRONTEND_DEV_SYNC_TEST_SERVE_PORT);
});

test('FrontendDevSync ignores ENV_SERVER_SYNC in main .env', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env', "ENV_SERVER_SYNC=true\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session);

    expect($result['env_autodev'])->toBeFalse()
        ->and(file_get_contents($themePath . '/.env'))->toBe("ENV_SERVER_SYNC=true\n");
});

test('FrontendDevSync npmDevEnvironment injects VITE keys without writing env files', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', FRONTEND_DEV_SYNC_TEST_SERVE_PORT, 'com_demo_app', true);

    $npmEnv = FrontendDevSync::npmDevEnvironment($config, null, 'com_demo_app', $session, $themePath);

    expect($npmEnv['VITE_DEV_PORT'])->toBe((string) $session->vitePort)
        ->and($npmEnv['VITE_SERVER_URL'])->toBe('http://127.0.0.1:' . FRONTEND_DEV_SYNC_TEST_SERVE_PORT)
        ->and($npmEnv['VITE_DEV_SERVER'])->toBe($session->viteDevServerUrl())
        ->and(is_file($themePath . '/.env'))->toBeFalse()
        ->and(is_file($themePath . '/.env.local'))->toBeFalse();
});

test('FrontendDevSync initThemeEnv copies .env.example to .env.local only', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/.env.example', "VITE_DEV_PORT=5199\n");

    expect(FrontendDevSync::initThemeEnv($themePath))->toBeTrue()
        ->and(is_file($themePath . '/.env.local'))->toBeTrue()
        ->and(is_file($themePath . '/.env'))->toBeFalse()
        ->and(file_get_contents($themePath . '/.env.local'))->toBe("VITE_DEV_PORT=5199\n");
});

test('FrontendDevSync adds vite plugin dependency without seeding env on sync', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env.example', "VITE_DEV_PORT=5199\n");
    file_put_contents($themePath . '/package.json', json_encode([
        'private' => true,
        'devDependencies' => [],
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");

    $config = FrontendConfig::forThemePath($themePath);
    $corePath = dirname(__DIR__, 3);

    $result = FrontendDevSync::sync($themePath, $config, $corePath, null, true);

    expect($result['vite_plugin'])->toBeTrue()
        ->and($result['vite_plugin_added'])->toBeTrue()
        ->and($result['env_seeded'])->toBeFalse()
        ->and($result['dev_state_path'])->toBe('.pinoox/dev.json')
        ->and(is_file($themePath . '/vite.pinoox.mjs'))->toBeFalse()
        ->and(is_file($themePath . '/.env'))->toBeFalse()
        ->and(is_file($themePath . '/.env.local'))->toBeFalse()
        ->and(file_get_contents($themePath . '/package.json'))->toContain('@pinooxhq/vite-plugin');
});

test('FrontendConfig reads VITE_DEV_PORT from env', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $_ENV['VITE_DEV_PORT'] = '5199';
    $_SERVER['VITE_DEV_PORT'] = '5199';

    $config = FrontendConfig::forThemePath($themePath);

    expect(FrontendConfig::devPort($config))->toBe(5199);
});

test('FrontendDevState mirrors theme dev state into project registry', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;
    $projectRoot = dirname($themePath, 2);
    $registryPath = $projectRoot . '/.pinoox/dev.json';

    \Pinoox\Component\Template\Frontend\FrontendDevState::write(
        $themePath,
        viteUrl: 'http://127.0.0.1:5173',
        port: 5173,
        outDir: 'dist',
        projectRoot: $projectRoot,
    );

    expect(is_file($themePath . '/.pinoox/dev.json'))->toBeTrue()
        ->and(is_file($registryPath))->toBeTrue();

    $registry = json_decode((string) file_get_contents($registryPath), true);

    expect($registry['themes'] ?? [])->not->toBeEmpty();

    \Pinoox\Component\Template\Frontend\FrontendDevState::remove($themePath, $projectRoot);

    expect(is_file($themePath . '/.pinoox/dev.json'))->toBeFalse()
        ->and(is_file($registryPath))->toBeFalse();
});
