<?php

use Pinoox\Component\Template\Frontend\FrontendConfig;
use Pinoox\Component\Template\Frontend\FrontendDevSession;
use Pinoox\Component\Template\Frontend\FrontendDevSync;

test('FrontendDevSession builds locked serve URLs at PHP origin without app-router path', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions(
        'com_pinoox_manager',
        $config,
        '127.0.0.1',
        8000,
        'com_pinoox_manager@/manager',
        true,
    );

    expect($session->phpAppUrl)->toBe('http://127.0.0.1:8000')
        ->and($session->displayAppUrls())->toBe(['http://127.0.0.1:8000'])
        ->and($session->proxyPrefixes)->toContain('/api')
        ->and($session->proxyPrefixes)->not->toContain('/manager')
        ->and($session->viteDevServerUrl())->toBe('http://127.0.0.1:5173');
});

test('FrontendDevSync writes autodev env and can wire simple vite config', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env', "ENV_SERVER_SYNC=true\n");
    file_put_contents($themePath . '/vite.config.js', <<<'JS'
import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), '');

    return {
        plugins: [],
        server: {
            proxy: {
                '/api': env.VITE_SERVER_URL,
            },
        },
    };
});
JS);

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);
    $corePath = dirname(__DIR__, 3);

    $result = FrontendDevSync::sync($themePath, $config, $corePath, $session, true, '.env');

    expect($result['env_autodev'])->toBeTrue()
        ->and($result['env_file'])->toBe('.env')
        ->and($result['vite_wired'])->toBeTrue()
        ->and(is_file($themePath . '/.env'))->toBeTrue()
        ->and(file_get_contents($themePath . '/.env'))->toContain('@pinoox-fe-dev autogenerated')
        ->and(file_get_contents($themePath . '/vite.config.js'))->toContain('@pinooxhq/vite-plugin')
        ->and(file_get_contents($themePath . '/vite.config.js'))->toContain('pinooxHot')
        ->and(file_get_contents($themePath . '/vite.config.js'))->toContain('pinooxServer');
});

test('FrontendDevSync does not write autodev env unless ENV_SERVER_SYNC is true', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);

    $result = FrontendDevSync::sync($themePath, $config, dirname(__DIR__, 3), $session, false, '.env');

    expect($result['env_autodev'])->toBeFalse()
        ->and(is_file($themePath . '/.env'))->toBeFalse();
});

test('FrontendDevSync merges autodev block into existing .env without wiping custom keys', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env', "MY_CUSTOM_KEY=keep-me\nENV_SERVER_SYNC=true\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);

    FrontendDevSync::writeAutoDevEnv($themePath, $session, $config, '.env');

    $env = file_get_contents($themePath . '/.env');

    expect($env)->toContain('MY_CUSTOM_KEY=keep-me')
        ->and($env)->toContain('VITE_SERVER_URL=http://127.0.0.1:8000')
        ->and($env)->toContain('VITE_HOT_FILE=dist/hot')
        ->and($env)->toContain('@pinoox-fe-dev end');
});

test('FrontendDevSync wires nested server proxy block without syntax errors', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/vite.config.js', <<<'JS'
import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), '');

    return {
        plugins: [vue()],
        server: {
            proxy: {
                '/api': env.VITE_SERVER_URL,
            },
        },
    };
});
JS);

    expect(FrontendDevSync::applyViteConfigWiring($themePath))->toBeTrue();

    $config = file_get_contents($themePath . '/vite.config.js');

    expect($config)->toContain('@pinooxhq/vite-plugin')
        ->and($config)->toContain('pinooxHot')
        ->and($config)->toContain('server: pinooxServer(env),')
        ->and($config)->not->toMatch('/pinooxServer\(env\),\s*\n\s*\},/s')
        ->and(substr_count($config, '{'))->toBe(substr_count($config, '}'));
});

test('FrontendDevSync accepts custom env file name', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env.local', "ENV_SERVER_SYNC=true\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);

    FrontendDevSync::writeAutoDevEnv($themePath, $session, $config, '.env.local');

    expect(is_file($themePath . '/.env.local'))->toBeTrue()
        ->and(FrontendDevSync::normalizeEnvFile('.env.local'))->toBe('.env.local');
});

test('FrontendDevSession platform serve unlocks router and labels serve app', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions(
        'com_pinoox_manager',
        $config,
        '127.0.0.1',
        8000,
        FrontendDevSession::SERVE_PLATFORM,
        true,
    );

    expect($session->platformServe)->toBeTrue()
        ->and($session->serveAppLocked)->toBeFalse()
        ->and($session->serveAppLabel())->toBe('platform');

    $npmEnv = $session->npmEnvironment($config, [], $themePath);

    expect($npmEnv['VITE_SERVE_APP'])->toBe('platform');
});

test('FrontendDevSession npmEnvironment respects theme env values over auto resolution', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    file_put_contents($themePath . '/.env', "VITE_DEV_PORT=5999\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);
    $themeEnv = FrontendDevSync::parseThemeEnv($themePath, '.env');
    $npmEnv = $session->npmEnvironment($config, $themeEnv, $themePath);

    expect($npmEnv)->not->toHaveKey('VITE_DEV_PORT')
        ->and($npmEnv['VITE_SERVER_URL'])->toBe('http://127.0.0.1:8000');
});

test('FrontendDevSession npmEnvironment adds backend refresh globs for Flow routes and Controller', function () {
    $themePath = frontendDevSyncThemeDir();
    $GLOBALS['__frontendDevSyncThemePath'] = $themePath;
    $appPath = dirname(dirname($themePath));

    file_put_contents($themePath . '/frontend.config.php', "<?php\n\nreturn ['stack' => 'vue'];\n");
    mkdir($appPath . '/Flow', 0777, true);
    mkdir($appPath . '/routes', 0777, true);
    mkdir($appPath . '/router', 0777, true);
    mkdir($appPath . '/Controller', 0777, true);
    mkdir($appPath . '/Component', 0777, true);
    mkdir($appPath . '/Portal', 0777, true);
    mkdir($appPath . '/config', 0777, true);
    mkdir($appPath . '/lang', 0777, true);
    file_put_contents($appPath . '/Flow/AuthFlow.php', "<?php\n");
    file_put_contents($appPath . '/routes/web.php', "<?php\n");
    file_put_contents($appPath . '/Controller/HomeController.php', "<?php\n");
    file_put_contents($appPath . '/Component/Helper.php', "<?php\n");
    file_put_contents($appPath . '/app.php', "<?php\nreturn [];\n");

    $config = FrontendConfig::forThemePath($themePath);
    $session = FrontendDevSession::fromOptions('com_demo_app', $config, '127.0.0.1', 8000, 'com_demo_app', true);
    $npmEnv = $session->npmEnvironment($config, [], $themePath);

    expect($npmEnv)->toHaveKey('VITE_DEV_REFRESH')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/Flow/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/routes/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/router/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/Controller/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/Component/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/Portal/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/config/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/lang/')
        ->and($npmEnv['VITE_DEV_REFRESH'])->toContain('/app.php');
});
