<?php

namespace Pinoox\Component\Template\Frontend;

use Pinoox\Support\ProjectCli;

/**
 * Keeps Vite HMR assets in a theme aligned with pincore (hot plugin, optional .env seed).
 */
final class FrontendDevSync
{
    public const STUB_SHARED_RELATIVE = 'stubs/frontend/shared';

    /** @var array<string, string> stub filename => theme filename */
    private const PINOOX_BUNDLE_FILES = [
        'vite.pinoox.mjs' => 'vite.pinoox.mjs',
        'vite-import-hot.mjs' => 'vite-import-hot.mjs',
        'vite-plugin-pinoox-hot.mjs' => 'vite-plugin-pinoox-hot.mjs',
    ];

    public const DEFAULT_ENV_FILE = '.env';

    /** When `true` in theme `.env`, `fe dev` persists the autogenerated VITE_* block to disk. */
    public const ENV_SERVER_SYNC_KEY = 'ENV_SERVER_SYNC';

    private const AUTO_ENV_BEGIN = '# @pinoox-fe-dev autogenerated';

    private const AUTO_ENV_END = '# @pinoox-fe-dev end';

    /**
     * @return array{
     *     pinoox_bundle: bool,
     *     env_seeded: bool,
     *     hot_path: string,
     *     env_autodev: bool,
     *     env_file: string,
     *     vite_wired: bool,
     *     vite_inspection: array<string, mixed>
     * }
     */
    public static function sync(
        string $themePath,
        array $config,
        ?string $corePath = null,
        ?FrontendDevSession $session = null,
        bool $fixVite = false,
        ?string $envFile = null,
    ): array {
        $themePath = rtrim(str_replace('\\', '/', $themePath), '/');
        $corePath = $corePath ?? self::resolveCorePath();
        $envFile = self::normalizeEnvFile($envFile);
        $inspection = self::inspectViteConfig($themePath);

        if ($fixVite && !$inspection['wired']) {
            $inspection['patched'] = self::applyViteConfigWiring($themePath);
            $inspection = self::inspectViteConfig($themePath);
        }

        return [
            'pinoox_bundle' => self::syncPinooxBundles($themePath, $corePath, $config),
            'env_seeded' => self::seedThemeEnv($themePath),
            'hot_path' => FrontendConfig::hotRelativePath($config),
            'env_autodev' => $session !== null && self::shouldWriteAutoDevEnv($themePath, $envFile)
                ? self::writeAutoDevEnv($themePath, $session, $config, $envFile)
                : false,
            'env_file' => $envFile,
            'vite_wired' => $inspection['wired'],
            'vite_inspection' => $inspection,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function inspectViteConfig(string $themePath): array
    {
        $path = rtrim(str_replace('\\', '/', $themePath), '/') . '/vite.config.js';

        if (!is_file($path)) {
            return [
                'exists' => false,
                'has_pinoox_hot' => false,
                'has_pinoox_server' => false,
                'wired' => false,
            ];
        }

        $content = (string) file_get_contents($path);
        $hasHot = str_contains($content, 'pinooxHot') || str_contains($content, 'createPinooxViteConfig');
        $hasServer = str_contains($content, 'pinooxServer') || str_contains($content, 'createPinooxViteConfig');
        $hasRefresh = str_contains($content, 'pinooxRefresh') || str_contains($content, 'createPinooxViteConfig');

        return [
            'exists' => true,
            'has_pinoox_hot' => $hasHot,
            'has_pinoox_server' => $hasServer,
            'has_pinoox_refresh' => $hasRefresh,
            'wired' => $hasHot && $hasServer,
            'path' => $path,
        ];
    }

    public static function applyViteConfigWiring(string $themePath): bool
    {
        $path = rtrim(str_replace('\\', '/', $themePath), '/') . '/vite.config.js';

        if (!is_file($path)) {
            return false;
        }

        $content = (string) file_get_contents($path);
        $inspection = self::inspectViteConfig($themePath);

        if ($inspection['wired']) {
            return true;
        }

        $updated = $content;

        if (!$inspection['has_pinoox_hot'] && !$inspection['has_pinoox_server']) {
            $updated = "import pinooxHot, { pinooxServer } from './vite.pinoox.mjs';\n" . $updated;
        }

        if (!$inspection['has_pinoox_hot'] && preg_match('/plugins\s*:\s*\[/', $updated)) {
            $updated = (string) preg_replace(
                '/plugins\s*:\s*\[/',
                "plugins: [\n            pinooxHot(),",
                $updated,
                1,
            );
        }

        if (!$inspection['has_pinoox_server']) {
            $replaced = self::replaceServerBlock($updated, 'server: pinooxServer(env),');

            if ($replaced !== null) {
                $updated = $replaced;
            } elseif (!preg_match('/server\s*:/', $updated)) {
                $updated = (string) preg_replace(
                    '/return\s*\{/',
                    "return {\n        server: pinooxServer(env),",
                    $updated,
                    1,
                );
            }
        }

        $updated = self::cleanupOrphanServerBrace($updated);

        if ($updated === $content || !self::viteConfigLooksValid($updated)) {
            return false;
        }

        return file_put_contents($path, $updated) !== false;
    }

    private static function replaceServerBlock(string $content, string $replacement): ?string
    {
        if (!preg_match('/server\s*:\s*\{/', $content, $match, PREG_OFFSET_CAPTURE)) {
            return null;
        }

        $keyStart = $match[0][1];
        $bracePos = strpos($content, '{', $keyStart);

        if ($bracePos === false) {
            return null;
        }

        $end = self::findClosingBrace($content, $bracePos);

        if ($end === null) {
            return null;
        }

        $trailingComma = isset($content[$end + 1]) && $content[$end + 1] === ',' ? 1 : 0;

        return substr($content, 0, $keyStart)
            . $replacement
            . substr($content, $end + 1 + $trailingComma);
    }

    private static function findClosingBrace(string $content, int $openPos): ?int
    {
        $depth = 0;
        $length = strlen($content);
        $inString = false;
        $quote = '';

        for ($i = $openPos; $i < $length; $i++) {
            $char = $content[$i];

            if ($inString) {
                if ($char === '\\') {
                    $i++;

                    continue;
                }

                if ($char === $quote) {
                    $inString = false;
                }

                continue;
            }

            if ($char === '"' || $char === "'" || $char === '`') {
                $inString = true;
                $quote = $char;

                continue;
            }

            if ($char === '{') {
                $depth++;
            } elseif ($char === '}') {
                $depth--;

                if ($depth === 0) {
                    return $i;
                }
            }
        }

        return null;
    }

    private static function cleanupOrphanServerBrace(string $content): string
    {
        return (string) preg_replace(
            '/server:\s*pinooxServer\(env\),\s*\n\s*\},/s',
            'server: pinooxServer(env),',
            $content,
            1,
        );
    }

    private static function viteConfigLooksValid(string $content): bool
    {
        if (str_contains($content, 'pinooxServer(env),') && preg_match('/pinooxServer\(env\),\s*\n\s*\},/s', $content)) {
            return false;
        }

        $open = substr_count($content, '{');
        $close = substr_count($content, '}');

        return $open === $close && $open > 0;
    }

    public static function writeAutoDevEnv(
        string $themePath,
        FrontendDevSession $session,
        array $config,
        string $envFile = self::DEFAULT_ENV_FILE,
    ): bool {
        if (!self::shouldWriteAutoDevEnv($themePath, $envFile)) {
            return false;
        }

        $themePath = rtrim(str_replace('\\', '/', $themePath), '/');
        $envFile = self::normalizeEnvFile($envFile);
        $target = $themePath . '/' . $envFile;
        $block = self::buildAutoDevBlock($session, $config);
        $existing = is_file($target) ? (string) file_get_contents($target) : '';
        $merged = self::mergeAutoDevBlock($existing, $block);

        if ($existing === $merged) {
            return true;
        }

        return file_put_contents($target, $merged) !== false;
    }

    public static function hasAutoDevBlock(string $themePath, ?string $envFile = null): bool
    {
        $target = rtrim(str_replace('\\', '/', $themePath), '/') . '/' . self::normalizeEnvFile($envFile);

        if (!is_file($target)) {
            return false;
        }

        return str_contains((string) file_get_contents($target), self::AUTO_ENV_BEGIN);
    }

    public static function normalizeEnvFile(?string $envFile): string
    {
        $envFile = trim(str_replace('\\', '/', (string) ($envFile ?? self::DEFAULT_ENV_FILE)));
        $envFile = ltrim($envFile, '/');

        if ($envFile === '' || str_contains($envFile, '..') || str_contains($envFile, '/')) {
            return self::DEFAULT_ENV_FILE;
        }

        return $envFile;
    }

    /**
     * @return array<string, string>
     */
    public static function parseThemeEnv(string $themePath, ?string $envFile = null): array
    {
        $target = rtrim(str_replace('\\', '/', $themePath), '/') . '/' . self::normalizeEnvFile($envFile);

        if (!is_file($target)) {
            return [];
        }

        $parsed = [];

        foreach (preg_split('/\R/', (string) file_get_contents($target)) ?: [] as $line) {
            $line = trim($line);

            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }

            if (!str_contains($line, '=')) {
                continue;
            }

            [$key, $value] = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);

            if ($key === '') {
                continue;
            }

            if (
                (str_starts_with($value, '"') && str_ends_with($value, '"'))
                || (str_starts_with($value, "'") && str_ends_with($value, "'"))
            ) {
                $value = substr($value, 1, -1);
            }

            $parsed[$key] = $value;
        }

        return $parsed;
    }

    public static function shouldWriteAutoDevEnv(string $themePath, ?string $envFile = null): bool
    {
        $flag = strtolower(trim(self::parseThemeEnv($themePath, $envFile)[self::ENV_SERVER_SYNC_KEY] ?? 'false'));

        return in_array($flag, ['1', 'true', 'yes', 'on'], true);
    }

    /**
     * Inject only auto-resolved keys that are missing or empty in the theme `.env`.
     *
     * @param array<string, string> $auto
     * @param array<string, string> $themeEnv
     * @param list<string>          $forceKeys  auto values that override theme `.env` (dev:apps port allocation)
     *
     * @return array<string, string>
     */
    public static function mergeThemeEnvOverrides(array $auto, array $themeEnv, array $forceKeys = []): array
    {
        $merged = [];

        foreach ($auto as $key => $value) {
            $fromTheme = $themeEnv[$key] ?? null;

            if (!in_array($key, $forceKeys, true)
                && is_string($fromTheme)
                && trim($fromTheme) !== '') {
                continue;
            }

            $merged[$key] = $value;
        }

        return $merged;
    }

    private static function buildAutoDevBlock(FrontendDevSession $session, array $config): string
    {
        $lines = [
            self::AUTO_ENV_BEGIN,
            '# Regenerated on each `' . ProjectCli::autoFormat('fe dev') . '` run.',
            'VITE_HOT_FILE=' . FrontendConfig::hotRelativePath($config),
            'VITE_SERVER_URL=' . $session->phpAppUrl,
            'VITE_DEV_PORT=' . $session->vitePort,
            'VITE_DEV_SERVER=' . $session->viteDevServerUrl(),
        ];

        if ($session->proxyPrefixes !== []) {
            $lines[] = 'VITE_DEV_PROXY=' . implode(',', $session->proxyPrefixes);
        }

        $lines[] = self::AUTO_ENV_END;

        return implode("\n", $lines);
    }

    private static function mergeAutoDevBlock(string $content, string $block): string
    {
        $pattern = '/\n?' . preg_quote(self::AUTO_ENV_BEGIN, '/') . '.*?' . preg_quote(self::AUTO_ENV_END, '/') . '\n?/s';

        if (preg_match($pattern, $content)) {
            return rtrim((string) preg_replace($pattern, "\n" . $block . "\n", $content, 1)) . "\n";
        }

        $trimmed = rtrim($content);

        if ($trimmed === '') {
            return $block . "\n";
        }

        return $trimmed . "\n\n" . $block . "\n";
    }

    /**
     * @return list<array{level: string, message: string}>
     */
    public static function diagnose(string $themePath, array $config, ?FrontendDevSession $session = null): array
    {
        $issues = [];
        $inspection = self::inspectViteConfig($themePath);

        if (!FrontendConfig::usesViteAssets($config)) {
            $issues[] = ['level' => 'error', 'message' => 'Theme stack does not use Vite assets (stack: ' . ($config['stack'] ?? 'twig') . ').'];

            return $issues;
        }

        if (!is_file($themePath . '/package.json')) {
            $issues[] = ['level' => 'error', 'message' => 'package.json is missing in the theme folder.'];
        }

        if (!$inspection['exists']) {
            $issues[] = ['level' => 'error', 'message' => 'vite.config.js was not found.'];
        } elseif (!$inspection['wired']) {
            $issues[] = [
                'level' => 'warning',
                'message' => 'vite.config.js is not wired to pinooxHot/pinooxServer — HMR will not work. Run: ' . ProjectCli::autoFormat('fe dev --fix-vite'),
            ];
        }

        if (!is_file($themePath . '/vite.pinoox.mjs')) {
            $issues[] = ['level' => 'warning', 'message' => 'vite.pinoox.mjs is missing — it is auto-synced on fe dev/build.'];
        }

        $manifest = FrontendConfig::manifestAbsolutePath($themePath, $config);

        if ($manifest !== null && is_file($manifest) && !is_file(FrontendConfig::hotAbsolutePath($themePath, $config))) {
            $issues[] = [
                'level' => 'comment',
                'message' => 'Production manifest exists without a hot file — PHP may serve built assets until Vite starts.',
            ];
        }

        return $issues;
    }

    public static function stubSharedPath(?string $corePath = null): string
    {
        $corePath = $corePath ?? self::resolveCorePath();

        return rtrim(str_replace('\\', '/', $corePath), '/') . '/' . self::STUB_SHARED_RELATIVE;
    }

    public static function syncHotPlugin(string $themePath, ?string $corePath, array $config): bool
    {
        return self::syncPinooxBundles($themePath, $corePath, $config);
    }

    private static function syncPinooxBundles(string $themePath, ?string $corePath, array $config): bool
    {
        if (!FrontendConfig::usesViteAssets($config)) {
            return false;
        }

        $sharedRoot = self::stubSharedPath($corePath);
        $ok = true;

        foreach (self::PINOOX_BUNDLE_FILES as $stubFile => $themeFile) {
            $ok = self::syncBundleFile($themePath, $sharedRoot, $stubFile, $themeFile) && $ok;
        }

        return $ok;
    }

    private static function syncBundleFile(
        string $themePath,
        string $sharedRoot,
        string $stubFile,
        string $themeFile,
    ): bool {
        $source = $sharedRoot . '/' . $stubFile;

        if (!is_file($source)) {
            return false;
        }

        $target = rtrim(str_replace('\\', '/', $themePath), '/') . '/' . $themeFile;

        if (is_file($target) && hash_file('sha256', $target) === hash_file('sha256', $source)) {
            return true;
        }

        return copy($source, $target);
    }

    public static function seedThemeEnv(string $themePath): bool
    {
        $env = $themePath . '/.env';
        $example = $themePath . '/.env.example';

        if (is_file($env) || !is_file($example)) {
            return false;
        }

        return copy($example, $env);
    }

    public static function removeHotFile(string $themePath, array $config): void
    {
        $hotFile = FrontendConfig::hotAbsolutePath($themePath, $config);

        if (is_file($hotFile)) {
            @unlink($hotFile);
        }
    }

    /**
     * @return array<string, string>
     */
    public static function npmDevEnvironment(
        array $config,
        ?string $corePath = null,
        ?string $package = null,
        ?FrontendDevSession $session = null,
        ?string $themePath = null,
        ?string $envFile = null,
        array $forceEnvKeys = [],
    ): array {
        $themeEnv = $themePath !== null ? self::parseThemeEnv($themePath, $envFile) : [];

        if ($session !== null) {
            return $session->npmEnvironment($config, $themeEnv, (string) $themePath, $forceEnvKeys);
        }

        $env = [
            'VITE_HOT_FILE' => FrontendConfig::hotRelativePath($config),
            'PINOOX_CORE_PATH' => $corePath ?? self::resolveCorePath(),
            'VITE_DEV_PORT' => (string) FrontendConfig::devPort($config),
        ];

        $serverUrl = self::resolveAppServerUrl($package);

        if ($serverUrl !== null) {
            $env['VITE_SERVER_URL'] = $serverUrl;
        }

        $proxy = self::resolveDevProxyPrefixes($package);

        if ($proxy !== null) {
            $env['VITE_DEV_PROXY'] = $proxy;
        }

        return self::mergeThemeEnvOverrides($env, $themeEnv, $forceEnvKeys);
    }

    /**
     * Keys forced during `fe dev:apps` so each theme uses its allocated Vite port.
     *
     * @return list<string>
     */
    public static function stackForceEnvKeys(): array
    {
        return [
            'VITE_DEV_PORT',
            'VITE_DEV_SERVER',
            'VITE_SERVER_URL',
            'VITE_DEV_PROXY',
            'VITE_HOT_FILE',
        ];
    }

    private static function resolveDevProxyPrefixes(?string $package): ?string
    {
        if ($package === null || $package === '') {
            return null;
        }

        try {
            $paths = self::mountPathsForPackage($package);

            $transport = \Pinoox\Portal\App\AppEngine::config($package)->get('transport');

            if (is_array($transport)) {
                foreach (['auth_config', 'auth_cookie', 'user', 'session_token'] as $key) {
                    $linked = $transport[$key] ?? null;

                    if (!is_string($linked) || $linked === '' || $linked === 'platform') {
                        continue;
                    }

                    if (!\Pinoox\Portal\App\AppEngine::exists($linked)) {
                        continue;
                    }

                    $paths = array_merge($paths, self::mountPathsForPackage($linked));
                }
            }

            $paths = array_values(array_unique(array_filter($paths)));

            return $paths === [] ? null : implode(',', $paths);
        } catch (\Throwable) {
            return null;
        }
    }

    /**
     * @return list<string>
     */
    private static function mountPathsForPackage(string $package): array
    {
        $routes = \Pinoox\Portal\App\AppRouter::getByPackage($package);
        $paths = [];

        foreach (array_keys($routes) as $routePath) {
            $normalized = '/' . trim((string) $routePath, '/');

            if ($normalized !== '/') {
                $paths[] = $normalized;
            }
        }

        return $paths;
    }

    private static function resolveAppServerUrl(?string $package): ?string
    {
        if ($package === null || $package === '') {
            return null;
        }

        try {
            $url = \Pinoox\Portal\Url::appUrl($package);

            return is_string($url) && $url !== '' ? $url : null;
        } catch (\Throwable) {
            return null;
        }
    }

    public static function resolveCorePath(): string
    {
        if (defined('PINOOX_CORE_PATH')) {
            return rtrim(str_replace('\\', '/', (string) PINOOX_CORE_PATH), '/');
        }

        return dirname(__DIR__, 3);
    }
}
